name: Build and Deploy Lambda

on:
  push:
    paths:
      - 'src/lambda_package/**'
  workflow_dispatch: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1            
      ECR_REPOSITORY: tourism-experience   
      LAMBDA_FUNCTION: tourism_weekly_forecast 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        IMAGE_TAG=latest
        docker buildx build --platform linux/amd64 --provenance=false -f src/lambda_package/Dockerfile -t $ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:$IMAGE_TAG

    - name: Push Docker image to ECR
      run: |
        IMAGE_TAG=latest
        docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:$IMAGE_TAG

    - name: Update Lambda function
      run: |
        IMAGE_TAG=latest
        aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION \
          --image-uri ${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:$IMAGE_TAG
